import Image from 'next/image';
import React, {FC, memo} from 'react';

import {SectionId} from '../../data/data';
import airsim from '../../images/portfolio/drone/airsim.png';
import drone from '../../images/portfolio/drone/portfolio_drone.jpg';
import real from '../../images/portfolio/drone/real.jpg';
import Section from '../Layout/Section';

const About: FC = memo(() => {
  return (
    <Section className="bg-neutral-800 text-white" sectionId={SectionId.None}>
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="py-8 sm:py-12">
      <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-3 sm:mb-4">Undergraduate Project : Drone</h1>
      <p className="text-sm sm:text-base md:text-lg text-gray-300 mb-4 sm:mb-6">
          This project features a quadcopter UAV that utilizes lift generated by forward motion. 
          The drone's structure combines 3D-printed parts and carbon fiber, 
          equipped with various sensors, controllers, and a 4S battery. It runs on ROS implemented in Python, 
          with nodes for flight control and OpenCV-based image recognition. 
          The system is tested on a simulated course mirroring the TDK flying competition, including tasks like hovering, 
          line following, traffic light response, payload dropping, and landing. 
          This simulation aims to validate the program's real-world applicability, 
          laying groundwork for future applications in delivery, surveying, and tracking missions.
          </p>
          <div className="flex justify-center">
          <Image
                alt="Drone"
                className="rounded-lg"
                src={drone}
                width={600}
              />
          </div>
        </div>

        <div className="space-y-8 sm:space-y-12">
          <div className=" rounded-lg overflow-hidden">
            <div className="p-4 sm:p-6">
              <h2 className="text-lg sm:text-xl md:text-2xl font-semibold mb-2 sm:mb-3">Motivation</h2>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              Drone applications are expanding rapidly, from entertainment to military and industrial uses, 
              driving market growth. Taiwan's advantage in drone development stems from its strong ICT industry, 
              providing key components like batteries, chips, cameras, and antennas. 
              This mature supply chain offers cost benefits in R&D. 
              Our research focuses on integrating stable drone flight and image recognition with ROS (Robot Operating System). 
              We aim to demonstrate our achievements by completing the TDK flying competition course. 
              This project leverages Taiwan's ICT strengths to advance drone technology, 
              particularly in flight stability and computer vision, 
              potentially leading to broader industrial applications and innovations in the drone sector.
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-8 sm:space-y-12">
          <div className=" rounded-lg overflow-hidden">
            <div className="p-4 sm:p-6">
              <h2 className="text-lg sm:text-xl md:text-2xl font-semibold mb-2 sm:mb-3">Teamwork</h2>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              The project initially split into mechanical design and programming phases. 
              The drone's structure was conceived after studying various designs, then modeled in Solidworks and 3D printed. 
              Programming began with image recognition and flight control using Airsim's environment and API.
              </p>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              Later, the team decided to use ROS and MAVROS for physical control. 
              Team members independently studied required knowledge, 
              sharing progress and challenges in regular meetings. 
              Problem-solving followed a "share-when-solved" approach, 
              with solutions discussed in meetings for efficient collaboration.
              </p>
              <div className="flex justify-center">
              <Image
                alt="Drone"
                className="rounded-lg"
                src={airsim}
                width={500}
              />
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-8 sm:space-y-12">
          <div className=" rounded-lg overflow-hidden">
            <div className="p-4 sm:p-6">
              <h2 className="text-lg sm:text-xl md:text-2xl font-semibold mb-2 sm:mb-3">Result</h2>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              This project successfully assembled a quadcopter drone using Pixhawk 4 Mini as the flight control core, 
              with QGroundControl as the ground control station. 
              The drone integrates Jetson Xavier NX, optical flow sensor, LiDAR, IMX219-120 Camera, 
              and OpenCV for autonomous flight and image recognition.
              </p>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              Key challenges addressed:
              </p>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              1. Image Recognition: To mitigate shadow interference and unclear recognition during flight, the image is segmented into multiple sections, reducing the risk of interference.
              </p>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              2. Stable Flight: For indoor flights where GPS is unavailable, optical flow and LiDAR sensors were added to achieve stable takeoff and flight.
              </p>
              <p className="text-xs sm:text-sm md:text-base mb-3">
              These solutions enhance the drone's performance in image processing and flight stability, particularly in GPS-denied environments.
              </p>
              <div className="flex justify-center">
              <Image
                alt="Drone"
                className="rounded-lg"
                src={real}
                width={500}
              />
              </div>
            </div>
          </div>
        </div>


        <div className="mt-12">
          <h2 className="text-2xl font-semibold mb-4 text-center">Final Project Video</h2>
          <div className="relative w-full" style={{paddingBottom: '50%'}}>
            <iframe
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
              className="absolute top-0 left-0 w-full h-full rounded-lg"
              src="https://www.youtube.com/embed/SnAItE21r1Y?si=ugppkcLb9JNmK2lK"
            ></iframe>
          </div>
        </div>
      </div>
    </Section>
  );
});

About.displayName = 'About';
export default About;